name: Code Quality - SonarQube

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  sonar:
    name: Build and Analyze
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Configurar JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17' 
          distribution: 'zulu'
          cache: maven

      - name: Cache dos pacotes do Sonar
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Build e Análise do Sonar
        env:
          SONAR_TOKEN: ${{ secrets.SONARTOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io
        run: mvn -B verify sonar:sonar -Dsonar.projectKey= br.org.edu.ifrn:LojaCarro
